version: "3.9"

services:
  backend:
    build:
      context: ./backend   
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - hr-ai-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    networks:
      - hr-ai-net
    depends_on:
      - backend

networks:
  hr-ai-net:
    driver: bridge
